name: portfolio_v2
description: "A new Flutter project."

# Prevents accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^5.0.0
  font_awesome_flutter: ^10.4.0
  url_launcher: ^6.1.7
  cupertino_icons: ^1.0.8
  http: ^1.1.0
  flutter_staggered_grid_view: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  cached_network_image: ^3.2.3

flutter:
  uses-material-design: true

  assets:
    - web/icons/portfolio.png
    - web/icons/portfolio_light.png
    - assets/
    - assets/clickhere.gif
artifacts:
    baseDirectory: build/web
    files:
      - '**/*'